# commodore-64 — Classic C64 blue screen, pale blue text and cyan highlights
# cmus color theme | NIRU CMUS THEMES 1.0.0
set color_win_fg=lightblue
set color_win_bg=blue
set color_title_fg=white
set color_title_bg=blue
set color_statusline_fg=blue
set color_statusline_bg=lightblue
set color_cmdline_fg=white
set color_cmdline_bg=blue
set color_error=lightred
set color_info=lightcyan
set color_separator=lightblue
set color_win_cur=white
set color_win_cur_sel=blue
set color_win_sel_fg=blue
set color_win_sel_bg=lightblue
set color_win_dir=lightcyan
set color_win_artist=white
set color_win_title=lightblue
set color_win_album=lightcyan
set color_win_time=white
set color_win_time_sel=blue
