# hackerwoman — Electric magenta, violet and cyan on black
# cmus color theme | NIRU CMUS THEMES 1.0.0
set color_win_fg=lightgray
set color_win_bg=black
set color_title_fg=lightmagenta
set color_title_bg=black
set color_statusline_fg=black
set color_statusline_bg=lightmagenta
set color_cmdline_fg=lightcyan
set color_cmdline_bg=black
set color_error=lightred
set color_info=lightcyan
set color_separator=magenta
set color_win_cur=lightmagenta
set color_win_cur_sel=black
set color_win_sel_fg=black
set color_win_sel_bg=lightmagenta
set color_win_dir=lightcyan
set color_win_artist=lightmagenta
set color_win_title=white
set color_win_album=lightcyan
set color_win_time=magenta
set color_win_time_sel=black
