# niru-noir — Minimal monochrome, graphite and restrained silver
# cmus color theme | NIRU CMUS THEMES 1.0.0
set color_win_fg=lightgray
set color_win_bg=black
set color_title_fg=white
set color_title_bg=darkgray
set color_statusline_fg=white
set color_statusline_bg=darkgray
set color_cmdline_fg=white
set color_cmdline_bg=black
set color_error=lightred
set color_info=lightgray
set color_separator=darkgray
set color_win_cur=white
set color_win_cur_sel=black
set color_win_sel_fg=black
set color_win_sel_bg=lightgray
set color_win_dir=white
set color_win_artist=lightgray
set color_win_title=white
set color_win_album=lightgray
set color_win_time=darkgray
set color_win_time_sel=black
