# satie — Quiet ivory, soft piano-grey and understated warmth
# cmus color theme | NIRU CMUS THEMES 1.0.0
set color_win_fg=lightgray
set color_win_bg=black
set color_title_fg=white
set color_title_bg=blue
set color_statusline_fg=white
set color_statusline_bg=blue
set color_cmdline_fg=white
set color_cmdline_bg=black
set color_error=lightred
set color_info=lightgray
set color_separator=blue
set color_win_cur=white
set color_win_cur_sel=black
set color_win_sel_fg=black
set color_win_sel_bg=white
set color_win_dir=lightcyan
set color_win_artist=lightgray
set color_win_title=white
set color_win_album=lightgray
set color_win_time=cyan
set color_win_time_sel=black
